/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import Entidades.Producto;
import AccesoDatos.ProductoData;

/**
 *
 * @author elihe
 */
public class FormularioProductos extends javax.swing.JInternalFrame {
    private ProductoData produData=new ProductoData();
    private Producto productoActual=null;

    /**
     * Creates new form FormularioProductos
     */
    public FormularioProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLproducto = new javax.swing.JLabel();
        JTnombre = new javax.swing.JTextField();
        JTdescripcion = new javax.swing.JTextField();
        JTprecioactual = new javax.swing.JTextField();
        JLnombre = new javax.swing.JLabel();
        JBbuscar = new javax.swing.JButton();
        JLdescripcion = new javax.swing.JLabel();
        JLprecioactual = new javax.swing.JLabel();
        JLstock = new javax.swing.JLabel();
        JBnuevo = new javax.swing.JButton();
        JBeliminar = new javax.swing.JButton();
        JBguardar = new javax.swing.JButton();
        JBsalir = new javax.swing.JButton();
        JTstock = new javax.swing.JTextField();
        JRBestado = new javax.swing.JRadioButton();
        JLestado = new javax.swing.JLabel();
        JTcodigo = new javax.swing.JTextField();
        JLcodigo = new javax.swing.JLabel();

        JLproducto.setText("♦ PRODUCTO ♦");

        JTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTnombreActionPerformed(evt);
            }
        });

        JLnombre.setText("♦ Nombre:");

        JBbuscar.setText("Buscar");
        JBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbuscarActionPerformed(evt);
            }
        });

        JLdescripcion.setText("♦ Descripción:");

        JLprecioactual.setText("♦ Precio Actual:");

        JLstock.setText("♦ Stock:");

        JBnuevo.setText("Nuevo");
        JBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnuevoActionPerformed(evt);
            }
        });

        JBeliminar.setText("Eliminar");
        JBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBeliminarActionPerformed(evt);
            }
        });

        JBguardar.setText("Guardar");
        JBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarActionPerformed(evt);
            }
        });

        JBsalir.setText("Salir");
        JBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalirActionPerformed(evt);
            }
        });

        JLestado.setText("♦ Estado:");

        JTcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcodigoActionPerformed(evt);
            }
        });

        JLcodigo.setText("♦ Código:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLdescripcion)
                                    .addComponent(JLprecioactual)
                                    .addComponent(JLnombre)
                                    .addComponent(JLstock)
                                    .addComponent(JLestado)
                                    .addComponent(JLcodigo))
                                .addGap(42, 42, 42))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBnuevo)
                                .addGap(18, 18, 18)
                                .addComponent(JBeliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(15, 15, 15)
                        .addComponent(JBguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(JBsalir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLproducto)
                            .addComponent(JTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTprecioactual, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTstock, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRBestado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBbuscar)))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLcodigo)
                    .addComponent(JBbuscar))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLnombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLdescripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTprecioactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLprecioactual))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLstock))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLestado)
                    .addComponent(JRBestado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBnuevo)
                    .addComponent(JBeliminar)
                    .addComponent(JBguardar)
                    .addComponent(JBsalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnombreActionPerformed

    private void JBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBeliminarActionPerformed
        // TODO add your handling code here:
        if(productoActual!=null){
            produData.eliminarProducto(productoActual.getIdProducto());
            productoActual=null;
            limpiarCampos();
            
        
        }else{
            JOptionPane.showMessageDialog(this,"No hay producto seleccionado");
        }
     
         
    }//GEN-LAST:event_JBeliminarActionPerformed

    private void JBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JBsalirActionPerformed

    private void JBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbuscarActionPerformed
        // TODO add your handling code here:
       try{
            Integer codigo=Integer.parseInt(JTcodigo.getText());
//            
              productoActual=produData.buscarProducto(codigo);
            if(productoActual!=null){
                JTnombre.setText(productoActual.getNombreProducto());
                JTdescripcion.setText(productoActual.getDescripcion());
                JTprecioactual.setText(Integer.toString(productoActual.getPrecioActual()));
                JTstock.setText(Integer.toString(productoActual.getStock()));
                JRBestado.setSelected(productoActual.isEstado());
                
                
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Debe ingresar un número válido");
        }
        
    }//GEN-LAST:event_JBbuscarActionPerformed

    private void JTcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcodigoActionPerformed

    private void JBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnuevoActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        productoActual=null;
        
    }//GEN-LAST:event_JBnuevoActionPerformed

    private void JBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarActionPerformed
        // TODO add your handling code here:
       try{
            Integer codigo=Integer.parseInt(JTcodigo.getText());
            String nombre=JTnombre.getText();
            String descripcion=JTdescripcion.getText();
            Integer precio=Integer.parseInt(JTprecioactual.getText());
            Integer stock=Integer.parseInt(JTstock.getText());
            Boolean estado=JRBestado.isSelected();
            if(nombre.isEmpty()){
             JOptionPane.showMessageDialog(this, "No puede haber campos vacíos");
             return;
            }
            
            if(productoActual==null){
                productoActual=new Producto(codigo,nombre,descripcion,precio,stock,estado);
                produData.resgistrarProducto(productoActual);
            }else{
                productoActual.setIdProducto(codigo);
                productoActual.setNombreProducto(nombre);
                productoActual.setDescripcion(descripcion);
                productoActual.setPrecioActual(precio);
                productoActual.setStock(stock);
                productoActual.setEstado(estado);
                                
                produData.modificarProducto(productoActual);
                
            }
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Debe ingresar un Código válido");
        }
        
    }//GEN-LAST:event_JBguardarActionPerformed
private void limpiarCampos(){
        JTcodigo.setText("");
        JTnombre.setText("");
        JTdescripcion.setText("");
        JTprecioactual.setText("");
        JTstock.setText("");
        JRBestado.setSelected(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBbuscar;
    private javax.swing.JButton JBeliminar;
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBnuevo;
    private javax.swing.JButton JBsalir;
    private javax.swing.JLabel JLcodigo;
    private javax.swing.JLabel JLdescripcion;
    private javax.swing.JLabel JLestado;
    private javax.swing.JLabel JLnombre;
    private javax.swing.JLabel JLprecioactual;
    private javax.swing.JLabel JLproducto;
    private javax.swing.JLabel JLstock;
    private javax.swing.JRadioButton JRBestado;
    private javax.swing.JTextField JTcodigo;
    private javax.swing.JTextField JTdescripcion;
    private javax.swing.JTextField JTnombre;
    private javax.swing.JTextField JTprecioactual;
    private javax.swing.JTextField JTstock;
    // End of variables declaration//GEN-END:variables
}
