/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author elihe
 */
public class FormularioProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioProveedor
     */
    public FormularioProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLproveedor = new javax.swing.JLabel();
        JTrazonsocial = new javax.swing.JTextField();
        JTdomicilio = new javax.swing.JTextField();
        JTtelefono = new javax.swing.JTextField();
        JBnuevo = new javax.swing.JButton();
        JBeliminar = new javax.swing.JButton();
        JBbuscar = new javax.swing.JButton();
        JBguardar = new javax.swing.JButton();
        JBsalir = new javax.swing.JButton();
        JLrazonsocial = new javax.swing.JLabel();
        JLdomicilio = new javax.swing.JLabel();
        JLtelefono = new javax.swing.JLabel();

        JLproveedor.setText("PROVEEDOR");

        JTrazonsocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTrazonsocialActionPerformed(evt);
            }
        });

        JTtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTtelefonoActionPerformed(evt);
            }
        });

        JBnuevo.setText("Nuevo");
        JBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnuevoActionPerformed(evt);
            }
        });

        JBeliminar.setText("Eliminar");

        JBbuscar.setText("Buscar");

        JBguardar.setText("Guardar");

        JBsalir.setText("Salir");

        JLrazonsocial.setText("Razon Social:");

        JLdomicilio.setText("Domicilio:");

        JLtelefono.setText("Telefono:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(JLrazonsocial))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLdomicilio)
                            .addComponent(JLtelefono)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBnuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBeliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTdomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLproveedor)
                    .addComponent(JTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBguardar)
                            .addComponent(JTrazonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBbuscar)
                            .addComponent(JBsalir))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JTrazonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBbuscar)
                        .addComponent(JLrazonsocial))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLproveedor)
                        .addGap(61, 61, 61)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTdomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLdomicilio))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLtelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBnuevo)
                    .addComponent(JBeliminar)
                    .addComponent(JBguardar)
                    .addComponent(JBsalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTrazonsocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTrazonsocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTrazonsocialActionPerformed

    private void JTtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTtelefonoActionPerformed

    private void JBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBnuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBbuscar;
    private javax.swing.JButton JBeliminar;
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBnuevo;
    private javax.swing.JButton JBsalir;
    private javax.swing.JLabel JLdomicilio;
    private javax.swing.JLabel JLproveedor;
    private javax.swing.JLabel JLrazonsocial;
    private javax.swing.JLabel JLtelefono;
    private javax.swing.JTextField JTdomicilio;
    private javax.swing.JTextField JTrazonsocial;
    private javax.swing.JTextField JTtelefono;
    // End of variables declaration//GEN-END:variables
}
